[package]
name = "bevy_entitiles_derive"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/443eb9/bevy_entitiles"
description = "Derive macros for bevy_entitiles"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.40"
proc-macro2 = "1.0.70"
