[package]
name = "bevy_entitiles_derive"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/443eb9/bevy_entitiles"
description = "Derive macros for bevy_entitiles"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "2"
proc-macro2 = "1"
